/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarshalRouteImport } from './routes/marshal'
import { Route as PatrollerRouteImport } from './routes/patroller'
import { Route as RegisterOwnerRouteImport } from './routes/register-owner'
import { Route as SubheadRouteImport } from './routes/subhead'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOwnersRouteImport } from './routes/admin/owners'
import { Route as AdminPatrolRouteImport } from './routes/admin/patrol'
import { Route as AdminSubheadsRouteImport } from './routes/admin/subheads'
import { Route as AdminTeamRouteImport } from './routes/admin/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalRoute = MarshalRouteImport.update({
  id: '/marshal',
  path: '/marshal',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrollerRoute = PatrollerRouteImport.update({
  id: '/patroller',
  path: '/patroller',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOwnerRoute = RegisterOwnerRouteImport.update({
  id: '/register-owner',
  path: '/register-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SubheadRoute = SubheadRouteImport.update({
  id: '/subhead',
  path: '/subhead',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOwnersRoute = AdminOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatrolRoute = AdminPatrolRouteImport.update({
  id: '/patrol',
  path: '/patrol',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubheadsRoute = AdminSubheadsRouteImport.update({
  id: '/subheads',
  path: '/subheads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/marshal': typeof MarshalRoute
  '/patroller': typeof PatrollerRoute
  '/register-owner': typeof RegisterOwnerRoute
  '/subhead': typeof SubheadRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/patrol': typeof AdminPatrolRoute
  '/admin/subheads': typeof AdminSubheadsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marshal': typeof MarshalRoute
  '/patroller': typeof PatrollerRoute
  '/register-owner': typeof RegisterOwnerRoute
  '/subhead': typeof SubheadRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/patrol': typeof AdminPatrolRoute
  '/admin/subheads': typeof AdminSubheadsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/marshal': typeof MarshalRoute
  '/patroller': typeof PatrollerRoute
  '/register-owner': typeof RegisterOwnerRoute
  '/subhead': typeof SubheadRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/patrol': typeof AdminPatrolRoute
  '/admin/subheads': typeof AdminSubheadsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/marshal'
    | '/patroller'
    | '/register-owner'
    | '/subhead'
    | '/admin/owners'
    | '/admin/patrol'
    | '/admin/subheads'
    | '/admin/team'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/marshal'
    | '/patroller'
    | '/register-owner'
    | '/subhead'
    | '/admin/owners'
    | '/admin/patrol'
    | '/admin/subheads'
    | '/admin/team'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/marshal'
    | '/patroller'
    | '/register-owner'
    | '/subhead'
    | '/admin/owners'
    | '/admin/patrol'
    | '/admin/subheads'
    | '/admin/team'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarshalRoute: typeof MarshalRoute
  PatrollerRoute: typeof PatrollerRoute
  RegisterOwnerRoute: typeof RegisterOwnerRoute
  SubheadRoute: typeof SubheadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal': {
      id: '/marshal'
      path: '/marshal'
      fullPath: '/marshal'
      preLoaderRoute: typeof MarshalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patroller': {
      id: '/patroller'
      path: '/patroller'
      fullPath: '/patroller'
      preLoaderRoute: typeof PatrollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-owner': {
      id: '/register-owner'
      path: '/register-owner'
      fullPath: '/register-owner'
      preLoaderRoute: typeof RegisterOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subhead': {
      id: '/subhead'
      path: '/subhead'
      fullPath: '/subhead'
      preLoaderRoute: typeof SubheadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/owners': {
      id: '/admin/owners'
      path: '/owners'
      fullPath: '/admin/owners'
      preLoaderRoute: typeof AdminOwnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patrol': {
      id: '/admin/patrol'
      path: '/patrol'
      fullPath: '/admin/patrol'
      preLoaderRoute: typeof AdminPatrolRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subheads': {
      id: '/admin/subheads'
      path: '/subheads'
      fullPath: '/admin/subheads'
      preLoaderRoute: typeof AdminSubheadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOwnersRoute: typeof AdminOwnersRoute
  AdminPatrolRoute: typeof AdminPatrolRoute
  AdminSubheadsRoute: typeof AdminSubheadsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOwnersRoute: AdminOwnersRoute,
  AdminPatrolRoute: AdminPatrolRoute,
  AdminSubheadsRoute: AdminSubheadsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MarshalRoute: MarshalRoute,
  PatrollerRoute: PatrollerRoute,
  RegisterOwnerRoute: RegisterOwnerRoute,
  SubheadRoute: SubheadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
